name: Release
on:
  workflow_dispatch:
  schedule:
    - cron: "30 4 * * *"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Get latest go version
        id: version
        run: |
          echo "go_version=$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g')" >> $GITHUB_ENV
      
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go_version }}

      - name: Compare latest tags and set variables
        run: |
          upstreamLatestTag=$(curl https://api.github.com/repos/Dreamacro/maxmind-geoip/releases/latest | grep "tag_name" | cut -d\" -f4)
          thisLatestTag=$(curl https://api.github.com/repos/${{ github.repository }}/releases/latest | grep "tag_name" | cut -d\" -f4)
          if [[ $upstreamLatestTag != $thisLatestTag ]]; then
            echo "NeedToSync=true" >> $GITHUB_ENV
          fi
          echo "RELEASE_NAME=$upstreamLatestTag" >> $GITHUB_ENV
          echo "TAG_NAME=$upstreamLatestTag" >> $GITHUB_ENV

      - name: Build geoip
        if: ${{ env.NeedToSync }}
        id: build
        run: go run . -v
        
      - name: Generate sha256 hash
        if: ${{ env.NeedToSync }}
        run: |
          ls
          sha256sum geoip.db > geoip.db.sha256sum
          sha256sum geoip-cn.db > geoip-cn.db.sha256sum

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
           geoip*